export default [
  "Take a deep breath and notice the feeling of the air entering your lungs.",
  "What is one thing you are grateful for today?",
  "Close your eyes for a moment and listen to the sounds around you.",
  "Think of a happy memory. Let it fill you with warmth.",
  "Stretch your arms above your head and feel the release in your shoulders.",
  "Notice the taste and texture of your next sip of water.",
  "Look out a window and find one beautiful thing in nature.",
  "Place your hand on your heart and feel its steady beat.",
  "Unclench your jaw and relax your shoulders.",
  "What is a simple pleasure you can enjoy today?",
  "Think of someone who makes you smile.",
  "Take a moment to simply be, without any agenda.",
  "What is one small act of kindness you can do for someone today?",
  "Focus on your breath for five full inhales and exhales.",
  "Notice the colors in the room around you.",
  "What is a song that always lifts your spirits?",
  "Think about a challenge you've overcome. Acknowledge your strength.",
  "What does 'peace' feel like in your body?",
  "Allow yourself a moment of stillness.",
  "What is one thing you can let go of right now?",
  "Imagine your worries floating away like clouds in the sky.",
  "Take a slow, mindful walk, even if it's just for a minute.",
  "What is a scent that brings you comfort?",
  "Think of a quality you admire in yourself.",
  "What is one thing you're looking forward to?",
  "Send a silent 'thank you' to your body for all it does.",
  "What is a small, achievable goal you can set for yourself today?",
  "Focus on the sensation of your feet on the ground.",
  "What is a positive affirmation that resonates with you?",
  "Allow yourself to do nothing for a full minute. Just breathe."
]
